# Generated by Django 6.0.7 on 2026-07-28 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='easiness',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='card',
            name='interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='lapses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='repetitions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grade', models.PositiveIntegerField()),
                ('easiness_after', models.FloatField()),
                ('repetitions_after', models.PositiveIntegerField()),
                ('interval_days_after', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='decks.card')),
            ],
            options={
                'ordering': ['-reviewed_at', '-id'],
            },
        ),
    ]
