# Generated by Django 6.0.7 on 2026-07-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_review_grade_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_grade_between_0_and_5',
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.PositiveIntegerField(),
        ),
    ]
