# Generated by Django 6.0.7 on 2026-07-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_restore_review_grade_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='folder',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
