# Generated by Django 6.0.7 on 2026-07-29 05:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_add_deck_sharing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='grading_mode',
            field=models.CharField(blank=True, choices=[('', 'Use account default'), ('anki', 'Four grades'), ('simple', 'Pass/fail')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='deck',
            name='new_card_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='review_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_reviews', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('max_new_cards', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('grading_mode', models.CharField(choices=[('anki', 'Four grades'), ('simple', 'Pass/fail')], default='anki', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
