# Generated by Django 6.0.7 on 2026-07-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_add_study_settings'),
    ]

    operations = [
        # Every existing card becomes a basic front/back card. The additive
        # defaults keep this migration deployable without rewriting or losing
        # any learner-authored card content or scheduling history.
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('reversible', 'Reversible'), ('multiple_choice', 'Multiple choice'), ('cloze', 'Cloze deletion'), ('image', 'Image')], default='basic', max_length=24),
        ),
        migrations.AddField(
            model_name='card',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='card',
            name='correct_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
